name: text-linter
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: |
            *.md
            !test/*.md
